### ISSUE TITLE
Feature request: Passing custom headers

### ISSUE THREAD

**Issue by nikkatalnikov** [MatrixTM/MHDDoS#207]
It would be great to pass custom headers to the tool. 

I can take a lead on implementation. How would you prefer to implement it in terms of API?

```
--header <str>
```

as the last param (L7 attacks only)?

**Comment by Nexuzzzz** [comment]
add a header file with customizable placeholders, for example:
```
User-Agent: $useragent
referer: https://google.com
DNT: 1
```

where $useragent is randomly picked
