### ISSUE TITLE
Sugetion - Improve script to bypass Cloudflare etc

### ISSUE THREAD

**Issue by andress134** [MatrixTM/MHDDoS#239]
Hello, i see the script still use old lib 'cfscrape' this lib can't bypass any challenge.
My sugestion is to improve the script to use https://github.com/ultrafunkamsterdam/undetected-chromedriver
You will use it just to generate a browser emulator and get cookies / pass the challenge 

1, start the script call (define the status code 503 - 403 etc) or check in header if target is cloudflare
2 call to undetected-chromedriver start the browser session pass the challenge and get cookies
3 return the cookies / token and use it to make ddos attack

**Comment by Shesui** [comment]
Waiting for update this the good script
