### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by sova32** [MatrixTM/MHDDoS#312]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
Operating System: openSUSE Tumbleweed 20220330
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.16.15-1-default (64-bit)
Graphics Platform: X11
Processors: 2 × AMD A4-6300 APU with Radeon(tm) HD Graphics
Memory: 13.6 ГиБ of RAM
Graphics Processor: AMD ARUBA
Python 3.8.12
```

### What happened (Describe the bug) ?

A bug happened!

### Screenshots

https://i.imgur.com/LnRDPSh.png

### Relevant log output

```shell
[BUG Report]:
```

### Your code

```true
with sudo

vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> pip3 install pyroxy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyroxy in /home/vadiki/.local/lib/python3.8/site-packages (1.0b4)
Requirement already satisfied: maxminddb>=2.2.0 in /home/vadiki/.local/lib/python3.8/site-packages (from pyroxy) (2.2.0)
Requirement already satisfied: pysocks>=1.7.1 in /usr/lib/python3.8/site-packages (from pyroxy) (1.7.1)
Requirement already satisfied: requests>=2.27.1 in /usr/lib/python3.8/site-packages (from pyroxy) (2.27.1)
Requirement already satisfied: yarl>=1.7.2 in /home/vadiki/.local/lib/python3.8/site-packages (from pyroxy) (1.7.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (1.26.7)
Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (3.3)
Requirement already satisfied: multidict>=4.0 in /home/vadiki/.local/lib/python3.8/site-packages (from yarl>=1.7.2->pyroxy) (6.0.2)
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> sudo pip3 install pyroxy
[sudo] пароль для root: 
Requirement already satisfied: pyroxy in /usr/local/lib/python3.8/site-packages (0.1)
Requirement already satisfied: bottle in /usr/local/lib/python3.8/site-packages (from pyroxy) (0.12.19)
Requirement already satisfied: lxml in /usr/local/lib64/python3.8/site-packages (from pyroxy) (4.8.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> sudo python3 start.py dns 185.63.191.14:53 256 600 resolvers.txt
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> 

without sudo
[16:45:57 - ERROR] Cannot Create Raw Socket
```

**Comment by Professor500** [comment]
> ### Version
> 2.4 (Default)
> 
> ### Which section is the problem?
> L4 (DDoS Attack Layer 4)
> 
> ### Please complete the following information
> ```
> Operating System: openSUSE Tumbleweed 20220330
> KDE Plasma Version: 5.24.3
> KDE Frameworks Version: 5.92.0
> Qt Version: 5.15.2
> Kernel Version: 5.16.15-1-default (64-bit)
> Graphics Platform: X11
> Processors: 2 × AMD A4-6300 APU with Radeon(tm) HD Graphics
> Memory: 13.6 ГиБ of RAM
> Graphics Processor: AMD ARUBA
> Python 3.8.12
> ```
> 
> ### What happened (Describe the bug) ?
> A bug happened!
> 
> ### Screenshots
> https://i.imgur.com/LnRDPSh.png
> 
> ### Please provide a link to a minimal reproduction of the bug
> _No response_
> 
> ### Relevant log output
> ```shell
> [BUG Report]:
> ```
> 
> ### Additional context
> _No response_
> 
> ### Your code
> ```
> with sudo
> 
> vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> pip3 install pyroxy
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: pyroxy in /home/vadiki/.local/lib/python3.8/site-packages (1.0b4)
> Requirement already satisfied: maxminddb>=2.2.0 in /home/vadiki/.local/lib/python3.8/site-packages (from pyroxy) (2.2.0)
> Requirement already satisfied: pysocks>=1.7.1 in /usr/lib/python3.8/site-packages (from pyroxy) (1.7.1)
> Requirement already satisfied: requests>=2.27.1 in /usr/lib/python3.8/site-packages (from pyroxy) (2.27.1)
> Requirement already satisfied: yarl>=1.7.2 in /home/vadiki/.local/lib/python3.8/site-packages (from pyroxy) (1.7.2)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (2021.10.8)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (1.26.7)
> Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (2.0.12)
> Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.27.1->pyroxy) (3.3)
> Requirement already satisfied: multidict>=4.0 in /home/vadiki/.local/lib/python3.8/site-packages (from yarl>=1.7.2->pyroxy) (6.0.2)
> vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> sudo pip3 install pyroxy
> [sudo] пароль для root: 
> Requirement already satisfied: pyroxy in /usr/local/lib/python3.8/site-packages (0.1)
> Requirement already satisfied: bottle in /usr/local/lib/python3.8/site-packages (from pyroxy) (0.12.19)
> Requirement already satisfied: lxml in /usr/local/lib64/python3.8/site-packages (from pyroxy) (4.8.0)
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> sudo python3 start.py dns 185.63.191.14:53 256 600 resolvers.txt
> Traceback (most recent call last):
>   File "start.py", line 27, in <module>
>     from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
> ModuleNotFoundError: No module named 'PyRoxy'
> vadiki@localhost:/run/media/vadiki/D_238_GB_WD/Кибервойска/DDoS/MHDDoS_proxy/MHDDoS> 
> 
> without sudo
> [16:45:57 - ERROR] Cannot Create Raw Socket
> ```

Have you already installed the requirements? or what do you mean

**Comment by MHProDev** [comment]
https://github.com/MHProDev/MHDDoS/wiki/installation

**Comment by MHProDev** [comment]
install with `sudo pip install -r requirements.txt`
