### ISSUE TITLE
discord 

### ISSUE THREAD

**Issue by Professor500** [MatrixTM/MHDDoS#317]
Hi can you fix the discord url on MatrixTM? url is not valid

**Comment by Xoosz** [comment]
WHERE DISCORD CHANNEL?

**Comment by Atager228** [comment]
discord channel was blocked

**Comment by Arman2122** [comment]
Discord channel was blocked by Discord team
Our new support and communicate will be on telegram group
so just wait our announce for Matrix community platform and invite link
Best regards.
@Professor500 @Xoosz @Atager228
