### ISSUE TITLE
[BUG Report]: ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)

### ISSUE THREAD

**Issue by 3raden** [MatrixTM/MHDDoS#321]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

ImportError: cannot import name 'Proxy' from 'PyRoxy' (unknown location)

### Screenshots

https://i.imgur.com/PVgGUvd.png

**Comment by Charles-McDaniel** [comment]
Hehe monkey balls
