### ISSUE TITLE
layer 4 Feature request

### ISSUE THREAD

**Issue by babodai** [MatrixTM/MHDDoS#325]
### Which section is this feature request for?

L4 (DDoS Attack Layer 4)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I think now is the time

### Describe the solution you'd like

new layer 4 scripts should arrive
for example, spoof udp/tcp ovh bypass nfo bypass
or amp/game
ts3 cs1.6 fivem etc..

**Comment by bntr00t** [comment]
Spoofed methods? For what, this is a script made to be used on all kind of servers and not only spoofed ones. For spoofed scripts you need iphm enabled servers
