### ISSUE TITLE
CFB - Outdated Method

### ISSUE THREAD

**Issue by ThatUncreativeDude** [MatrixTM/MHDDoS#336]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I was viewing the source code until I realised you were using the cfscrape library. This is a poor method of bypassing Cloudflare.

### Describe the solution you'd like

Replace CFScrape with another solution.

**Comment by bntr00t** [comment]
Some solutions would be

https://github.com/vvanglro/cf_clearance

Or even

https://github.com/VeNoMouS/cloudscraper

Which is in the python version still being actively updated.
