### ISSUE TITLE
Bug Report: MCBOT chat

### ISSUE THREAD

**Issue by flechabenx** [MatrixTM/MHDDoS#338]
When a minecraft bot joins the server it can't chat. I'm using this code:
```
Tools.send(s, Minecraft.login(f"{ProxyTools.Random.rand_str(9)}"))
sleep(1.5)
Tools.send(s, Minecraft.chat('/register something something'))
```

The server console says: 
```
UpstreamBridge - could not decode packet! java.lang.IllegalArgumentException: Decompressed size 1 less than compression threshold 256
disconnected with: DecoderException : java.lang.IllegalArgumentException: Decompressed size 1 less than compression threshold 256 @ io.netty.handler.codec.MessageToMessageDecoder:98
```

Even with the default MHDDoS code, it doesn't work.

**Comment by KhaledIsCool** [comment]
what

**Comment by KhaledIsCool** [comment]
what the hell this has to do with anything

**Comment by MHProDev** [comment]
1.8.9 protocol

**Comment by flechabenx** [comment]
> what the hell this has to do with anything

MHDDoS offers the MCBOT method which I am asking for support, what are you talking about?

**Comment by MHProDev** [comment]
Fixed in:
https://github.com/MatrixTM/MHDDoS/commit/140b7bf666f9883ca8d07014283ee1e5e82cb7e0
https://github.com/MatrixTM/MHDDoS/commit/17a5431ac29b7c8a379f4b32e2450ada13985a62

**Comment by flechabenx** [comment]
Thanks
