### ISSUE TITLE
[BUG Report]:Layer 4 Methods give me this error-Cannot Create Raw Socket-

### ISSUE THREAD

**Issue by huntergins4376** [MatrixTM/MHDDoS#340]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: windows 10-Chrome Shell Terminal
- Installed Requirements Version latest and greatest
- Python Version python3 latest
```

### What happened (Describe the bug) ?

cant send Layer 4 attacks maybe I have something wrong in the typing I will provide here, For proxied L4
python3 start.py NTP 174.86.140.34:80 1000 300 5 socks5.txt

### Screenshots

https://imgur.com/a/1PvMT6m

### Please provide a link to a minimal reproduction of the bug

blank

### Relevant log output

```shell
blank
```

### Additional context

blank

### Your code

```true
blank
```

**Comment by Jqnvier** [comment]
Use MHDDoS on VPS

**Comment by MHProDev** [comment]
run with sudo if windows run as administrator

**Comment by anoda69** [comment]
when i run in sudo I get :
Traceback (most recent call last):
  File "/home/kali/MHDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'

**Comment by codinggg** [comment]
@CseatPlanner switch to root, you need install requirements.txt again
