### ISSUE TITLE
BUG Report]:cannot run start.py issue in line 27 no module named PyRoxy

### ISSUE THREAD

**Issue by Crisinel** [MatrixTM/MHDDoS#341]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: Win11
- Installed Requirements Version PyRoxy
- Python Version 3.8x
```

### What happened (Describe the bug) ?

cannot run start.py

### Screenshots

www.google.com

### Please provide a link to a minimal reproduction of the bug

www.google.com

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\sus\OneDrive\Desktop\MHDDoS-2.4\MHDDoS-2.4\start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

**Comment by mrzt721010** [comment]
https://github.com/MatrixTM/MHDDoS/wiki/installation
