### ISSUE TITLE
[BUG Report]:cannot run start.py, error in  line 31 in module not found cloudscraper

### ISSUE THREAD

**Issue by Crisinel** [MatrixTM/MHDDoS#342]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS:win11
- Installed Requirements Version cloudscraper
- Python Version 3.8x
```

### What happened (Describe the bug) ?

cannot run start.py

### Screenshots

www.google.com

### Please provide a link to a minimal reproduction of the bug

www.google.com

### Relevant log output

```shell
line 31, in <module>
    from cloudscraper import create_scraper
ModuleNotFoundError: No module named 'cloudscraper'
```

**Comment by mrzt721010** [comment]
https://github.com/MatrixTM/MHDDoS/wiki/installation

**Comment by BelieveInBunny** [comment]
It isn't fixed, I get the same isue
Traceback (most recent call last):
  File "start.py", line 31, in <module>
    from cloudscraper import create_scraper
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by DenisovDenisA** [comment]
+

**Comment by DevProdj** [comment]
pip uninstall cloudscraper

python3 -m pip install git+https://github.com/VeNoMouS/cloudscraper
