### ISSUE TITLE
Termux Tutorial

### ISSUE THREAD

**Issue by sinaj2889** [MatrixTM/MHDDoS#343]
### Which section is this feature request for?

Other

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I sometimes get errors when installing on Termux but it was something with Cargo Build

### Describe the solution you'd like

So may you make a tutorial for termux too, bc especially at the ukraine and russia cyber war many people work from theyre phone too.

**Comment by mrzt721010** [comment]
https://github.com/MatrixTM/MHDDoS/wiki/installation

**Comment by sinaj2889** [comment]
This doesnt relate to termux
