### ISSUE TITLE
Traceback (most recent call last):   File "/home/lazaridilazare8/MHDDoS/start.py", line 1486, in <module>     HttpFlood(thread_id, url, host, method, rpc, event,   File "/usr/lib/python3.9/threading.py", line 874, in start     _start_new_thread(self._bootstrap, ()) RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Lazzex** [MatrixTM/MHDDoS#347]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. Kali linux google cloud shell terminal]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.9.2]
```

### What happened (Describe the bug) ?

A bug happened!
![Screenshot_1](https://user-images.githubusercontent.com/104001090/170665622-b02e9246-5018-4832-8c59-2c80bb204470.png)

### Screenshots

https://imgur.com/a/a9Yi4U2

### Relevant log output

```shell
File "/home/USER/MHDDoS/start.py", line 1486, in <module>
    HttpFlood(thread_id, url, host, method, rpc, event,
  File "/usr/lib/python3.9/threading.py", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

### Additional context

Please help me fix this bug also fix cloudfare bypass its not effective

**Comment by MHProDev** [comment]
ulimit -n 999999
![image](https://user-images.githubusercontent.com/63018646/176949770-5becedd8-3cd1-45f5-9153-91766055dd33.png)
65500 thread ? :\ check warning
![image](https://user-images.githubusercontent.com/63018646/176949832-1aa6a9c6-65eb-4ea0-bc13-2b8ddf9619db.png)
