### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by texas-john** [MatrixTM/MHDDoS#349]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: Ubuntu
- Installed Requirements Version 
- Python Version 3.8
```

### What happened (Describe the bug) ?

Whenever I run the script, this error shows:
Traceback (most recent call last):
  File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
So I commented out the import and even more if these errors occur with other imports.
I've seen that you have closed other issues similar to this, but this is a problem.

### Screenshots

a

### Please provide a link to a minimal reproduction of the bug

a

### Relevant log output

```shell
Traceback (most recent call last):
  File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

### Additional context

a

### Your code

```true
a
```

**Comment by vailouk** [comment]
> ### Version
> 2.4 (Default)
> 
> ### Which section is the problem?
> Script Base
> 
> ### Please complete the following information
> ```
> - OS: Ubuntu
> - Installed Requirements Version 
> - Python Version 3.8
> ```
> 
> ### What happened (Describe the bug) ?
> Whenever I run the script, this error shows: Traceback (most recent call last): File "start.py", line 28, in from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles ModuleNotFoundError: No module named 'PyRoxy' So I commented out the import and even more if these errors occur with other imports. I've seen that you have closed other issues similar to this, but this is a problem.
> 
> ### Screenshots
> a
> 
> ### Please provide a link to a minimal reproduction of the bug
> a
> 
> ### Relevant log output
> ```shell
> Traceback (most recent call last):
>   File "start.py", line 28, in <module>
>     from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
> ModuleNotFoundError: No module named 'PyRoxy'
> ```
> 
> ### Additional context
> a
> 
> ### Your code
> ```
> a
> ```

Not tobe version 2.3.4

**Comment by MHProDev** [comment]
check wiki
