### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by kubsakkk** [MatrixTM/MHDDoS#351]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: [Ubuntu]
- Installed Requirements Version [all]
- Python Version [3.10.1]
```

### What happened (Describe the bug) ?

A bug happened!
when trying syn from layer4 there is an error
File "/home/ubuntu/Desktop/MHDDoS/start.py", line 1521, in <module>
    __ip__ = getMyIPAddress()
NameError: name 'getMyIPAddress' is not defined
![image](https://user-images.githubusercontent.com/74510831/171288867-6a74c6ae-7e92-4a0f-92b6-3bfba3ad5afe.png)
when i try without the sudo there is an error cant create raw socket

### Screenshots

attached above

### Please provide a link to a minimal reproduction of the bug

sudo python3.10 start.py syn ip:port time

### Relevant log output

```shell
File "/home/ubuntu/Desktop/ddos/start.py", line 1521, in <module>
    __ip__ = getMyIPAddress()
NameError: name 'getMyIPAddress' is not defined
```

### Your code

```true
sudo python3.10 start.py syn ip:port time
python3.10 start.py syn ip:port time
```

**Comment by MHProDev** [comment]
update ur files
