### ISSUE TITLE
MCBE Layer 4 Proxy

### ISSUE THREAD

**Issue by zvy5** [MatrixTM/MHDDoS#353]
It would be good to implement proxy to L4 of MCPE, so attacking servers with pocketmine software would block many external IP's. I tried to try but it directly prints me that it is not possible to use proxy in that type of layer.

**Comment by MHProDev** [comment]
some proxies dosn't support udp we can't implement  that option if realy need this method telegram @MHProDev  or discord MH_ProDev#3893
