### ISSUE TITLE
I couldn't start the attack

### ISSUE THREAD

**Issue by rootlightman** [MatrixTM/MHDDoS#355]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I couldn't start the attack

### Describe the solution you'd like

 would appreciate it very much if you write the attack codes of the program

 L7: python3 start.py <method> <url> <socks_type> <threads> <proxylist> <rpc> <duration> <debug=optional>

you wrote like this, but I couldn't do it, can you make an example of it?

### Additional context

![1](https://user-images.githubusercontent.com/103443027/174781069-bd381eb6-2681-47ad-bc0d-af54ab7ba9b7.PNG)

**Comment by lidarbtc** [comment]
You can refer wiki page.

**Comment by MHProDev** [comment]
https://github.com/MatrixTM/MHDDoS/wiki
