### ISSUE TITLE
[BUG Report]: When i attack a certain IP instead of the other person lag it's me who suffers the attack

### ISSUE THREAD

**Issue by Benji105** [MatrixTM/MHDDoS#359]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: Windows 10
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version 3.10
```

### What happened (Describe the bug) ?

When i ddos someone instead of the person lagging it's me who "suffers" the attack and i go up to 5000 ping and nothing happens to the other person.

### Screenshots

d

### Please provide a link to a minimal reproduction of the bug

d

### Relevant log output

```shell
d
```

### Additional context

I would like to know what is wrong or if i did something wrong

### Your code

```true
a
```

**Comment by bntr00t** [comment]
skiddy

**Comment by MHProDev** [comment]
script have usage for spamming use server for attack
