### ISSUE TITLE
HOW TO USE IT DOSENT SAY HOWWWWWWWW

### ISSUE THREAD

**Issue by Bypassme** [MatrixTM/MHDDoS#360]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
pls helppp
```

### What happened (Describe the bug) ?

A bug happened!

### Screenshots

sdsds

### Please provide a link to a minimal reproduction of the bug

dsdsdsd

### Relevant log output

```shell
sdsdsdd
```

### Additional context

sdsdsd

### Your code

```true
edsds
```

**Comment by bntr00t** [comment]
https://github.com/MatrixTM/MHDDoS/wiki

Skid
