### ISSUE TITLE
BOMB Not working anymore after latest commit

### ISSUE THREAD

**Issue by nirvash21** [MatrixTM/MHDDoS#362]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

BOMB not working!

Already installed Bombard using method stated in Wiki. But the script says bombardier is not installed. It was working before.

### Screenshots

https://prnt.sc/o1B2fMxnkyGB

### Relevant log output

```shell
user@server:~/MHDDoS# python3 start.py bomb https://example.com 0 50 proxy.txt 100 3600

Traceback (most recent call last):
  File "/root/MHDDoS/start.py", line 1568, in <module>
    assert (
AssertionError: Install bombardier: https://github.com/MHProDev/MHDDoS/wiki/BOMB-method
```

**Comment by MHProDev** [comment]
please look https://github.com/MHProDev/MHDDoS/wiki/BOMB-method

**Comment by nirvash21** [comment]
Hi,

Yes I have done it. Just like that. But Bombardier is not detected by the script.
