### ISSUE TITLE
Can I get in trouble for this?

### ISSUE THREAD

**Issue by Bmh8000** [MatrixTM/MHDDoS#365]
### Which section is this feature request for?

Tools

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Can I get in trouble for this?

### Describe the solution you'd like

Can I get in trouble for this?

### Additional context

Can I get in trouble for this?

**Comment by Nexuzzzz** [comment]
If you attack a host without asking for permission, yes you can get in serious trouble

**Comment by SHC-Anonymous** [comment]
> If you attack a host without asking for permission, yes you can get in serious trouble

All methods are not secure even if it is proxy it doesn't matter the request with the proxy ip can be queried with that certain time and so you can be traced. I also recommend only attacking with the TOR method.

**Comment by Nexuzzzz** [comment]
> > If you attack a host without asking for permission, yes you can get in serious trouble
> 
> All methods are not secure even if it is proxy it doesn't matter the request with the proxy ip can be queried with that certain time and so you can be traced. I also recommend only attacking with the TOR method.

while TOR shields your true IP very good, i do not recomment it for 3 reasons. 
1 - It will put a huge load on the TOR network, so you are indirectly attacking everybody else
2 - It can be very slow, and can greatly reduce the size of your attack
3 - TOR exit nodes are very easy to block, and a lot of DDoS protection systems have ready 2 go rules that block TOR nodes
