### ISSUE TITLE
Roblox DDOS

### ISSUE THREAD

**Issue by OceanHotelVibes** [MatrixTM/MHDDoS#366]
### Which section is this feature request for?

L4 (DDoS Attack Layer 4)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Again we want a Roblox DDOS Feature or a GameFlood Feature.

### Describe the solution you'd like

Just add it it. this has been requests twice.

### Additional context

N/A

**Comment by RandomVersion** [comment]
Dont you need accs to join roblox games?

**Comment by quanmanss11** [comment]
what is roblox

**Comment by quanmanss11** [comment]
a new game ?

**Comment by mikhailramlal** [comment]
> a new game ?

Roblox is a very popular game the initial release date was in 2006

**Comment by quanmanss11** [comment]
ok

**Comment by poopyhead121** [comment]
this isn't possible btw

**Comment by poopyhead121** [comment]
number one, i doubt the person asking this even has enough resources to flood a roblox game
number two, goodluck

**Comment by paxqp** [comment]
> this isn't possible btw

You can't just say it's not possible, anything is possible. LMAO
