### ISSUE TITLE
USING

### ISSUE THREAD

**Issue by ajunkdha** [MatrixTM/MHDDoS#372]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi there , do i need to use vpn?? 

### Describe the solution you'd like

I have think

**Comment by Nexuzzzz** [comment]
Run it from a VPS server, and don't run it from your own home connection
