### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by h253518892** [MatrixTM/MHDDoS#373]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: kali
- Installed Requirements Version [PyRoxy1.0b5]
- Python Version [3.9.10]
```

### What happened (Describe the bug) ?

A bug happened!
![C45D1BA7-79B0-4846-9872-B615DEF919F8](https://user-images.githubusercontent.com/99782519/179489502-47c7779d-c483-45e4-9554-698e9619d403.png)

### Screenshots

![C45D1BA7-79B0-4846-9872-B615DEF919F8](https://user-images.githubusercontent.com/99782519/179489502-47c7779d-c483-45e4-9554-698e9619d403.png)

### Relevant log output

```shell
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/tools/MHDDoS-2.4/./start.py", line 341, in run
    self.select(self._method)
  File "/tools/MHDDoS-2.4/./start.py", line 406, in select
    self._amp_payloads = cycle(self._generate_amp())
  File "/tools/MHDDoS-2.4/./start.py", line 539, in _generate_amp
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
```

**Comment by SHC-Anonymous** [comment]
> ### Version
> 2.4 (Default)
> 
> ### Which section is the problem?
> L4 (DDoS Attack Layer 4)
> 
> ### Please complete the following information
> ```
> - OS: kali
> - Installed Requirements Version [PyRoxy1.0b5]
> - Python Version [3.9.10]
> ```
> 
> ### What happened (Describe the bug) ?
> A bug happened! ![C45D1BA7-79B0-4846-9872-B615DEF919F8](https://user-images.githubusercontent.com/99782519/179489502-47c7779d-c483-45e4-9554-698e9619d403.png)
> 
> ### Screenshots
> ![C45D1BA7-79B0-4846-9872-B615DEF919F8](https://user-images.githubusercontent.com/99782519/179489502-47c7779d-c483-45e4-9554-698e9619d403.png)
> 
> ### Please provide a link to a minimal reproduction of the bug
> _No response_
> 
> ### Relevant log output
> ```shell
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/tools/MHDDoS-2.4/./start.py", line 341, in run
>     self.select(self._method)
>   File "/tools/MHDDoS-2.4/./start.py", line 406, in select
>     self._amp_payloads = cycle(self._generate_amp())
>   File "/tools/MHDDoS-2.4/./start.py", line 539, in _generate_amp
>     for ref in self._ref:
> TypeError: 'NoneType' object is not iterable
> ```
> 
> ### Additional context
> _No response_
> 
> ### Your code
> _No response_

For amplification attack you need a Spoofed Server(s)

**Comment by MHProDev** [comment]
check reflector files
