### ISSUE TITLE
Not Work > [BUG Report]:

### ISSUE THREAD

**Issue by ajunkdha** [MatrixTM/MHDDoS#375]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

A bug happened! All Sampel Script no working this web 
https:://tsunade.co 👈

From A to Z 

But another site is working 

### Screenshots

live ping

### Please provide a link to a minimal reproduction of the bug

train

### Relevant log output

```shell
normal
```

### Additional context

Hemmm

### Your code

```true
Python3 start CFB/DGB/ALL
```

**Comment by bntr00t** [comment]
Don't be a skid

**Comment by ajunkdha** [comment]
Wkwkkw faramish

**Comment by bntr00t** [comment]
What shitty language is that

**Comment by ajunkdha** [comment]
multi language bro, oh yes you are there what can we do on that site

**Comment by bntr00t** [comment]
We could not use a python script HAHAHAHA

**Comment by ajunkdha** [comment]
> We could not use a python script HAHAHAHA

![Screenshot_20220720-163028_Chrome](https://user-images.githubusercontent.com/95839753/180042606-af260c9a-fb72-4a48-82a6-3da2526e0835.jpg)
Sory im nuub

**Comment by ajunkdha** [comment]
Bacod si jancuk..sok gg aja

**Comment by tauseedzaman** [comment]
lol
