### ISSUE TITLE
[BUG Report]:Cannot Create Raw Socket

### ISSUE THREAD

**Issue by 13MrBlackCat13** [MatrixTM/MHDDoS#376]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: Ubuntu 
- Python Version 3.10
```

### What happened (Describe the bug) ?

python3 start.py MEM ip:port 0 100 socks5.txt 100 4000 true

### Screenshots

https://st.mrblackcat.dev/KTUU91/

**Comment by SudoLite** [comment]
U need spoofable servers for AMP Methods
