### ISSUE TITLE
[BUG Report]:a mistake of wiki.

### ISSUE THREAD

**Issue by glut410** [MatrixTM/MHDDoS#378]
### Version

2.4 (Default)

### Which section is the problem?

Wiki

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.10.4]
```

### What happened (Describe the bug) ?

just a small mistake

### Screenshots

https://user-images.githubusercontent.com/46321515/181033582-752137cc-e72f-4395-bf75-da230b7ad0d5.png

**Comment by glut410** [comment]
![harry](https://user-images.githubusercontent.com/46321515/181040603-16d57c21-0b09-4be2-9dd4-b4c8f5fa9941.png)

another mistake.

**Comment by SudoLite** [comment]
Fixed
