### ISSUE TITLE
[BUG Report]: PyRoxy

### ISSUE THREAD

**Issue by CamZ2004** [MatrixTM/MHDDoS#380]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [Cloud Shell]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.9.2]
```

### What happened (Describe the bug) ?

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python in /usr/lib/python2.7/lib-dynload (2.7.18)
trioxxejtm@cloudshell:~/MHDDoS$ python3 start.py 
Traceback (most recent call last):
  File "/home/trioxxejtm/MHDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'

### Screenshots

https://imgur.com/a/6PtF2R3

**Comment by MHProDev** [comment]
https://github.com/MatrixTM/MHDDoS/wiki/installation
