### ISSUE TITLE
[BUG Report]:PyRoxy error still

### ISSUE THREAD

**Issue by 023948799e213e21b53eb83785356208** [MatrixTM/MHDDoS#383]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]

P
```

### What happened (Describe the bug) ?

I tried reinstalling it but no work yes its compatible with termux

### Screenshots

https://ibb.co/xqdDf8F

### Please provide a link to a minimal reproduction of the bug

docs

### Relevant log output

```shell
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tmvenom/MHDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

### Additional context

a great ddos script to test my firewall

### Your code

```true
Yes
```

**Comment by QuantumNovice** [comment]
In codespace it gave the same error.
![image](https://user-images.githubusercontent.com/43876848/183495121-1a4e7005-77bc-4123-84e9-c05b0b5891d1.png)

It can be mitigated by using the following command
`pip3.8 install -r requirements.txt`
