### ISSUE TITLE
Layer4 Methods

### ISSUE THREAD

**Issue by YongSheng109** [MatrixTM/MHDDoS#389]
### Which section is this feature request for?

L4 (DDoS Attack Layer 4)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to use layer4 methods, but I found out that most of them need reflector files. I tried to get dns.txt, ntp.txt, etc. and succeeded, but when I tried to ddos, it says "reflector file not found" and I still haven't figured out how to layer4 ddos yet. If you can, you should add OVH bypass, Cloudflare bypass, Google Cloud bypass, etc.

### Describe the solution you'd like

(im use google cloud shell which doesnt support opening port (53) for the amp)

### Additional context

you should also update cloudflare bypass like Karma-DDoS tbh (bfm)

**Comment by Nexuzzzz** [comment]
A tip, don't use ampification methods on a public and free VPS such as google shell :/
