### ISSUE TITLE
PyProxy [Bug / Help]

### ISSUE THREAD

**Issue by quiiTT** [MatrixTM/MHDDoS#391]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
I am running Windows 11, Opera GX and using the 'shell.cloud.google' method.
```

### What happened (Describe the bug) ?

While i was doing everything mentioned in the tutorial, at 'python3 start.py' i get following error code:

```
raze0mail@cloudshell:~/MHDDoS$ python3 start.py 
Traceback (most recent call last):
  File "/home/raze0mail/MHDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

After that i tried installing via 'pip3 install' PyRoxy and also the others, if possible. As i runned it again it still didn't work.

I also screened errors shown in the console if needed (not to mention, i just started recently coding so I am quiet 'noobish').
Edit: Your Discord invite code is not valid anymore.

### Screenshots

https://i.imgur.com/zI5GDDE.png

**Comment by quiiTT** [comment]
I might fixed it by my self. I will update you later.

**Comment by MHProDev** [comment]
see wiki installation
