### ISSUE TITLE
Which vps sites do you recommend?

### ISSUE THREAD

**Issue by Chipsy99** [MatrixTM/MHDDoS#394]
### Which section is this feature request for?

Other

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

No

### Describe the solution you'd like

Which vps sites do you recommend?
Many companies do not allow logging out and the vps closes directly, which companies do you know or use?

**Comment by quanmanss11** [comment]
google cloud (newbie only)

**Comment by ZKSYNCDEV** [comment]
whatever, AWS, gcloud, ovh, leaseweb

**Comment by umarahmad200** [comment]
Free?
