### ISSUE TITLE
PyRoxy

### ISSUE THREAD

**Issue by xJoshy** [MatrixTM/MHDDoS#398]
Traceback (most recent call last):
  File "C:\Users\joshy\MHDDoS\start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'

I've downloaded it but it still says this. im pretty sure i downloaded it

**Comment by marvi3** [comment]
How did you solve this?

**Comment by mrzt721010** [comment]
> 

Just install the module named "PyRoxy"

**Comment by marvi3** [comment]
I did install it with pip install pyroxy but the error stays

**Comment by Azimiao111** [comment]
i have the same question，no idea
