### ISSUE TITLE
ModuleNotFoundError: No module named 'psutil._psutil_windows'

### ISSUE THREAD

**Issue by zhn0222** [MatrixTM/MHDDoS#409]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
- OS: [win10 Home 21H2 19044.1889]
- Installed Requirements Version [psutil-5.9.2.tar.gz ]
- Python Version [3.10.7]
```

### What happened (Describe the bug) ?

Hello author, what is the problem? How to solve it?
D:\MHDDoS-2.4>start.py
Traceback (most recent call last):
  File "D:\MHDDoS-2.4\start.py", line 34, in <module>
    from psutil import cpu_percent, net_io_counters, process_iter, virtual_memory
  File "D:\MHDDoS-2.4\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "D:\MHDDoS-2.4\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ModuleNotFoundError: No module named 'psutil._psutil_windows'

### Screenshots

Images cannot be uploaded

**Comment by ACSRailgun** [comment]
I'm having the same problem now. Did you solve it?
