### ISSUE TITLE
[BUG Report] When I Send DDos It Make My WIfi Stop Working 

### ISSUE THREAD

**Issue by NallaYoutuber** [MatrixTM/MHDDoS#412]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
as
```

### What happened (Describe the bug) ?

It make My Wifi Slow And Not Even Send A DDOS To a Server OR A Website 
Fucking Fake / Scammer TOOL

### Screenshots

as

### Please provide a link to a minimal reproduction of the bug

sa

### Relevant log output

```shell
as
```

### Additional context

sa

### Your code

```true
as
```

**Comment by Monkeyman1337s** [comment]
Lmao, this complain really?
U need to read or do some research.
u are sending an attack with your own wifi,
if you attack any website you will get tracked down easily. Stop using the tool before u get caught.

**Comment by BlackSnowDot** [comment]
wtf really? wifi?
