### ISSUE TITLE
[BUG Report]:The command line prompts that the attack was successful, but no attack was actually launched.

### ISSUE THREAD

**Issue by NianBroken** [MatrixTM/MHDDoS#419]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

The command line says the attack has started, but why does the number of connections in the monitoring station stay at 2. Did I enter the command incorrectly? Or is it because I am not using it in the right way?
In my opinion, its connection number should immediately soar to more than a thousand or even higher ah, why has been the number of 2?
![20221020185855](https://user-images.githubusercontent.com/57057288/196931065-dc17acc2-827f-43ee-ba56-15be898a3f00.jpg)
![20221020185844](https://user-images.githubusercontent.com/57057288/196931074-73f7f2de-f7a9-467e-a48d-c274a0388cda.jpg)

### Screenshots

https://user-images.githubusercontent.com/57057288/196931074-73f7f2de-f7a9-467e-a48d-c274a0388cda.jpg

### Please provide a link to a minimal reproduction of the bug

https://bbos.cat

### Relevant log output

```shell
suinian666@cloudshell:~/MHDDoS$ python start.py ovh https://bbos.cat 1 1000 socks5.txt 100 60
[10:52:26 - INFO] Proxy Count: 1,840
[10:52:26 - INFO] Attack Started to bbos.cat with OVH method for 60 seconds, threads: 1000!
suinian666@cloudshell:~/MHDDoS$
```

**Comment by Hackerreplit** [comment]
Is on protect  to use a bypass or cfb i think or cfbuam

**Comment by Hackerreplit** [comment]
I like to use a ubuntu on digital ocean but not on real attack i just to test to my website

**Comment by Nurlan199206** [comment]
use `true` for verbose

example: python3 start.py get https://google.com 5 500 socks5.txt 5000 10000 true

**Comment by YUYANG1229** [comment]
图一你是怎么打开的呀？
