### ISSUE TITLE
Guys please help me with amplification and DNS method.

### ISSUE THREAD

**Issue by felssxs** [MatrixTM/MHDDoS#420]
![Снимок экрана 2022-10-24 200856](https://user-images.githubusercontent.com/94239108/197606671-85eb9ad8-157e-4fc1-9811-e5ba2d13fcf3.png)
![Снимок экрана 2022-10-24 200928](https://user-images.githubusercontent.com/94239108/197606687-9695e222-c4a9-492f-a946-c835da6950ce.png)
![Снимок экрана 2022-10-24 201036](https://user-images.githubusercontent.com/94239108/197606693-90b51062-3e26-4709-9ac2-e9f529561a07.png)

Guys please help me with amplification and DNS method. I realized that I needed to scan something, and something seemed to work out for me, but it says that there are 3 days left. I don't know if I did something wrong. If someone can help, please help.
![Снимок экрана 2022-10-24 192317](https://user-images.githubusercontent.com/94239108/197598027-dbc05355-afa6-482e-857a-c9d212de6ccf.png)
![Снимок экрана 2022-10-24 192410](https://user-images.githubusercontent.com/94239108/197598161-b2968d9e-ee40-4714-8059-50fc03e35be2.png)

**Comment by Eyeball-Kun** [comment]
thanks for the free dns txt,

 i think you need to specify the dns method and you need to do the full path to the text, if you dont know how to do that type pwd, copy that and tag on dns.txt

hope this helps!

**Comment by zhouli01** [comment]
HI,
 I think The dns.txt file should be placed under files and  I succeeded
![image](https://user-images.githubusercontent.com/36073927/219539310-fbad0f80-ef63-467c-9121-5e927697ad3d.png)

**Comment by Eyeball-Kun** [comment]
i would advice against attacking cloudflare????? or using this for anything illegal????

**Comment by Gh0stD14l3r** [comment]
> thanks for the free dns txt,
> 
> i think you need to specify the dns method and you need to do the full path to the text, if you dont know how to do that type pwd, copy that and tag on dns.txt
> 
> hope this helps!

You can populate your own list... https://github.com/Gh0stD14l3r/DNS-Spoofable-UDP-Servers
