### ISSUE TITLE
Traceback (most recent call last):   File "/root/MHDDoS/start.py", line 1630, in <module>     uagents, referers, proxies).start()   File "/usr/lib/python3.10/threading.py", line 935, in start     _start_new_thread(self._bootstrap, ()) RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Kyjarrell** [MatrixTM/MHDDoS#430]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [kali linux]
- Installed Requirements Version [all of them even looked at other peoples tuts for this dd]
- Python Version [tried every working version]
```

### What happened (Describe the bug) ?

"Traceback (most recent call last):
  File "/root/MHDDoS/start.py", line 1630, in <module>
    uagents, referers, proxies).start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread"

happens for everything

### Screenshots

idk

### Please provide a link to a minimal reproduction of the bug

idk

### Relevant log output

```shell
idk
```

### Your code

```true
dont have one
```

**Comment by Kyjarrell** [comment]
happens with every layer is kali not meant to be used or what?

**Comment by Nfglotus666** [comment]
same with L4

**Comment by Kyjarrell** [comment]
if anybody can make a detailed tutorial and post the link here i would appreciate it maybe im doing something wrong or something like that but idk

**Comment by KaNNabysX** [comment]
Well it happened to me too, I kind of fixed it by disabling the maxim threads 

https://www.baeldung.com/linux/max-threads-per-process

Idk if it was from that but it worked for me.
