### ISSUE TITLE
[BUG Report]: Amplification error

### ISSUE THREAD

**Issue by KaNNabysX** [MatrixTM/MHDDoS#431]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: Debian
- Installed Requirements Version latest
- Python Version 3
```

### What happened (Describe the bug) ?

Well, when I try to use the 
 " zmap -p53 --output-filter='sport=53' -Mudp --probe-args=file:dns.pkt -f "saddr udp_pkt_size" -o dns.txt "
command I get this error 
![image](https://user-images.githubusercontent.com/79973445/204050721-70904599-e4e0-466d-894d-d62e2c1d0669.png)
I am trying to use it on a debian fresh server, so yeah.

### Screenshots

.

### Please provide a link to a minimal reproduction of the bug

.

### Relevant log output

```shell
root@vultr:~/MHDDoS# zmap -p53 --output-filter='sport=53' -Mudp --probe-args=file:dns.pkt -f "saddr udp_pkt_size" -o dns.txt
Nov 25 20:03:08.839 [INFO] zmap: output module: csv
Nov 25 20:03:08.839 [FATAL] udp: could not open UDP data file 'localtime'
```

### Additional context

nope

### Your code

```true
.
```

**Comment by 1-bytes** [comment]
I am having the same problem with my Kali and Ubuntu, wish someone could tell me how to fix it ...

**Comment by mynameistp** [comment]
Has anyone got it worked out? I've got it worked out. I don't know how

**Comment by mynameistp** [comment]
Does anyone have a solution? I have the same problem. I don't know how to solve it
