### ISSUE TITLE
[BUG Report]: CFBUAM did't work at all

### ISSUE THREAD

**Issue by lifefloating** [MatrixTM/MHDDoS#434]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
- OS: centos 7.9
- Installed Requirements Version as requirements.txt said
- Python Version 3.7
```

### What happened (Describe the bug) ?

A bug happened!
 python3 start.py CFBUAM https://stargate.cam 1 1080 proxy.txt 60 60

but did't work at all!!!
what about this issue  waiting for you answser  tks!!!!!
![image](https://user-images.githubusercontent.com/13827124/205283527-1c41c520-a1e2-4018-a970-ae0ff1037645.png)

### Screenshots

https://user-images.githubusercontent.com/13827124/205283527-1c41c520-a1e2-4018-a970-ae0ff1037645.png

**Comment by Mr-joep** [comment]
hey ty it on https://cyber-hub.pw/layer7.php

**Comment by lifefloating** [comment]
> hey ty it on https://cyber-hub.pw/layer7.php
python3 start.py CFBUAM  https://blog.bathtubbashing.xyz/ 1 500 proxy.txt 60 600
didnt work the same
u sure this script work or can bypass CF ？

![image](https://user-images.githubusercontent.com/13827124/205587465-97d7192a-a4b9-4b3a-90c5-48eadb5504b1.png)

**Comment by ghgiStudios** [comment]
The bypasses do not work, there all old and outdated and patched.

**Comment by lifefloating** [comment]
> The bypasses do not work, there all old and outdated and patched.

i think same with you,this project is play to the gallery
