### ISSUE TITLE
[BUG Report]:no such a file or directory

### ISSUE THREAD

**Issue by ChelzoO** [MatrixTM/MHDDoS#438]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

A bug happened! no such file or directory

### Screenshots

https://sun9-56.userapi.com/impg/YjL5hb1bSrSyI2aCEKkkV-4SXg82XcM66hrF2Q/XBw6sOWZ0a0.jpg?size=1280x720&quality=96&sign=a05e74e278b47638f43c5ace10491fae&type=album

**Comment by Dhyanpatelhaker** [comment]
boy s is small do capital
