### ISSUE TITLE
[BUG Report]: warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

### ISSUE THREAD

**Issue by quartzz720** [MatrixTM/MHDDoS#443]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: Windows 11 22621.963
- Installed Requirements Version urllib3 (1.26.13), chardet (5.1.0), charset_normalizer (2.0.12) 
- Python Version 3.9.13
```

### What happened (Describe the bug) ?

PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

### Screenshots

https://imgur.com/a/nVVmbxs

**Comment by ret7020** [comment]
This is not a problem of MHDDoS.
This is a problem in the conflict of installed versions of libraries.
Read error message. Reinstall `chardet` && `urllib3` with correct versions.

**Comment by yechielb2000** [comment]
It seems to happend because `requests` uses this library but with old version.

Try changing the version to latest ( 2.28.2 )

https://github.com/MatrixTM/MHDDoS/blob/6671497c3a4438644cbd825382c3b348ad91bde4/requirements.txt#L4
