### ISSUE TITLE
[BUG Report]:  PyRoxy module not found 

### ISSUE THREAD

**Issue by Dhyanpatelhaker** [MatrixTM/MHDDoS#446]
### Version

2.4 (Default)

### Which section is the problem?

Tools

### Please complete the following information

```true
- OS: MacOS Catalina
- Installed Requirements.txt
```

### What happened (Describe the bug) ?

A bug happened!

### Screenshots

1

### Relevant log output

```shell
home@homes-MacBook-Pro MHDDoS-main % python3 start.py tools              
Traceback (most recent call last):
  File "/Users/home/Desktop/MHDDoS-main/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

**Comment by ret7020** [comment]
Try to install manually.
`pip3 install git+https://github.com/MHProDev/PyRoxy.git`

**Comment by ret7020** [comment]
Have you tried to run python shell and check module import status and/or check installation via `pip`?

**Comment by ChrisKimZHT** [comment]
> Have you tried to run python shell and check module import status and/or check installation via `pip`?

same issue:

```
chriskim@ChrisKim-s2:~/MHDDoS$ python3 start.py 
Traceback (most recent call last):
  File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```
```
chriskim@ChrisKim-s2:~/MHDDoS$ pip list | grep PyRoxy
PyRoxy             1.0b5
```
```
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyRoxy'
```

**Comment by ChrisKimZHT** [comment]
I solve this problem using virtualenv. Maybe there are some conflicts with system packages.

**Comment by Z-Nado** [comment]
how do you use virtualnv, i'm trying to figure out the same issue here and i'm so lost.

**Comment by megbase1** [comment]
same here

**Comment by jemueldalino** [comment]
This worked for me

```
pip install --upgrade virtualenv
virtualenv -p $(which python3) my_ddos_env
cd my_ddos_env
source ./bin/activate
python3 ../start.py tools
```

**Comment by Z-Nado** [comment]
yeah that didn't help at all.

**Comment by PaltalkDDOS** [comment]
how to fix
run this command in the folder MHHDoS  ( sudo pip install -r requirements.txt )
For example:
xxxx@cloudshell:~/MHDDoS$  **sudo pip install -r requirements.txt**

**Comment by lukejames1111** [comment]
> how to fix run this command in the folder MHHDoS ( sudo pip install -r requirements.txt ) For example: xxxx@cloudshell:~/MHDDoS$ **sudo pip install -r requirements.txt**

Still the same result for me:

```
Traceback (most recent call last):
  File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

**Comment by PaltalkDDOS** [comment]
> Still the same result for me:

please delete it all and do it all over again like me
sudo apt update
ulimit -u999999
ulimit -n999999
git clone https://github.com/MatrixTM/MHDDoS.git
cd MHDDoS
sudo pip install -r requirements.txt
sudo pip3 install requests -U
done
___________________________________________
with L7 style, use normal command :
python3 start.py OVH http://www.xxx.com 5 1000 socks5.txt 100 100

with L4 attack, you have to add sudo in front
sudo python3 start.py DNS 1.2.3.4:186 1 100 dns.txt true.

_____________________________________________________
Note with Layer4 Amplification attack:  you must put the file dnd.txt in the path files

join the paltalk bot group, if you are a programmer 
https://groups.google.com/g/developerpaltalk

**Comment by mur4ashy** [comment]
Make sure to create a virtual environment for main.py
**pip install --upgrade virtualenv**

download the archive **https://github.com/MHProDev/PyRoxy.git**
copy all files to the project folder
do not replace files !

open the project main.py PyCharm Community Edition

everything worked for me. Assembled the **.exe** file
with the **pip install pyinstaller command**

**pyinstaller main.py**

I hope this will help you
