### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by cris840** [MatrixTM/MHDDoS#454]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: Windows Server 2019
- Installed Requirements Version All Lasted version
- Python Version 3.9.13
```

### What happened (Describe the bug) ?

python start.py DNS 90.239.39.109:53 4 60 AMP.txt
[02:53:09 - ERROR] [91mCannot Create Raw Socket[0m

### Screenshots

https://imgur.com/a/WW6C6gC

**Comment by darkanubis0100** [comment]
This is only for Spoofed servers, send normal L4 or use L7 instead (Execute as root)
