### ISSUE TITLE
You guys are the worst

### ISSUE THREAD

**Issue by Person0z** [MatrixTM/MHDDoS#468]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Honesly, screw you guys for enabling people to DDOS others, i run a free bot host which i found 5 accounts alts that we dont even allow running this attacking other people obv without consent on our machines, this is serous 

### Describe the solution you'd like

Screw You and remove this

### Additional context

a

**Comment by iloveyumyumshrimpnoodles** [comment]
In order to defend against DDoS attacks, tools need to be written so defenses can be made.
Because the IT world is constantly moving and updating, good guys need to write bad stuff IN ORDER to defend against it.
Hence why it SHOULDN'T be removed and you should just improve your security :)

**Comment by Person0z** [comment]
> In order to defend against DDoS attacks, tools need to be written so defenses can be made.
> Because the IT world is constantly moving and updating, good guys need to write bad stuff IN ORDER to defend against it.
> Hence why it SHOULDN'T be removed and you should just improve your security :)

I agree, however we are a FREE host using a python/JavaScript egg. Tell me how do we stop certain code from running via bash, there is absolutely no way too. Prove me wrong.

**Comment by iloveyumyumshrimpnoodles** [comment]
> > In order to defend against DDoS attacks, tools need to be written so defenses can be made.
> > Because the IT world is constantly moving and updating, good guys need to write bad stuff IN ORDER to defend against it.
> > Hence why it SHOULDN'T be removed and you should just improve your security :)
> 
> I agree, however we are a FREE host using a python/JavaScript egg. Tell me how do we stop certain code from running via bash, there is absolutely no way too. Prove me wrong.

Ratelimit how much bandwith can be abused. Introduce a whitelist, so bots can only request discord.com or some.api and need to request access if another link is being used.

Or you can upgrade to a paid service.
If you grant people free servers then they're going to be abused, 100%. Take a look at DigitalOcean and their droplets

**Comment by MD211211** [comment]
I personally agree with you, but this tool comes in handy to me because I use it to test my own ddos protection

**Comment by MD211211** [comment]
But i request you atleast make it so that you have to have a domain with an a record pointing to that server and the server your trying to ddos from ATLEAST

**Comment by nickjayr** [comment]
skill issue, cope,mald,seethe and dilate+L

**Comment by iloveyumyumshrimpnoodles** [comment]
> skill issue, cope,mald,seethe and dilate+L

What a good response, totally adds value to this issue

**Comment by mrzt721010** [comment]
...
