### ISSUE TITLE
make a tcp udp ovh bypass

### ISSUE THREAD

**Issue by MrBolot** [MatrixTM/MHDDoS#470]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

hey, i want to request some feature that tcp udp but on OVH / OVH-SAS/ OVH Game
i have been make some code to do but yeah , its not worked.

### Describe the solution you'd like

i will be waited for the new feature.

**Comment by quanmanss11** [comment]
If you know how OVH bypass works, you will understand this is not possible with a single computer or IP address to connect

**Comment by quanmanss11** [comment]
OVH servers can be very huge; most paid servers can handle 10 terabytes of packets per second or per minute. (I'm not talking about OVH servers, and this is a joke to make you understand that this is not simple.)

**Comment by quanmanss11** [comment]
![234234](https://user-images.githubusercontent.com/84491040/236637649-ce0af3a7-9107-4dcd-bfbe-f63eb2c57071.PNG)

**Comment by quanmanss11** [comment]
![awerwer](https://user-images.githubusercontent.com/84491040/236637725-bf288061-3077-499f-8cba-6a3d46a501f4.PNG)
![wervwevrew](https://user-images.githubusercontent.com/84491040/236637751-6c2e8210-7cc7-4f17-b33f-c11b46220ae4.PNG)

**Comment by quanmanss11** [comment]
A scammer can easily fake OVH bypass DDOS or a random TikTok video or something. I don't know, maybe you know. I guess most DDOS methods are mostly used to make multiple computers undetectable from anti-ddos or DDOS protection for minutes, hours, years, or forever if possible. Remember, I say this just to read and understand that this will not be 100% correct.

**Comment by quanmanss11** [comment]
You could find out quicker if you did more research than just used your old memory in your brain to understand new things that I guess you didn't know.

**Comment by quanmanss11** [comment]
simple example I was just killing time for my stupidity, and I'm human. Everything I know is based on my memory and research.
