### ISSUE TITLE
[BUG Report]: Python Missing

### ISSUE THREAD

**Issue by femb-y** [MatrixTM/MHDDoS#483]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: Windows 10
- Installed Requirements Version: Latest, tried default
- Python Version: 3.11.4
```

### What happened (Describe the bug) ?

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

https://cdn.discordapp.com/attachments/1079118792229134386/1125321260449153024/image.png
https://media.discordapp.net/attachments/1079118792229134386/1125321676956114944/image.png

### Screenshots

https://cdn.discordapp.com/attachments/1079118792229134386/1125321260449153024/image.png

### Relevant log output

```shell
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```

**Comment by snap80000** [comment]
literally just disable python in microsoft store - https://i.upload.systems/six/d5M0jvgx
once ur done u might have to put in PATH
