### ISSUE TITLE
mcpe ddos

### ISSUE THREAD

**Issue by pro751** [MatrixTM/MHDDoS#486]
### Which section is this feature request for?

Other

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

what method should I use to ddos minecraft bedrock edition server

### Describe the solution you'd like

give me sample text
python3 start.py <method> <ip> etc.

**Comment by GameAttacker** [comment]
python3 start.py MCBOT  IP:prot 927 60
