### ISSUE TITLE
No Module Named PyRoxy Error

### ISSUE THREAD

**Issue by meatballsong1** [MatrixTM/MHDDoS#494]
No Module Named PyRoxy Error
I've installed it on pip3, ran on python3 and python with no avail.

**Comment by sativa2d** [comment]
i have the same error anyone know the fix

**Comment by liuyuanjun520** [comment]
Download the original pyproxy code and install it using setup.py

**Comment by meatballsong1** [comment]
Ok.

**Comment by damonsalvatore666** [comment]
ModuleNotFoundError: No module named 'PyRoxy'
Getting the same issue. how to fix this.

**Comment by aaajjkk111** [comment]
I am using kali, and then I got the following error when running start.py    
Traceback (most recent call last):
  File "/home/kali/MHDDoS/start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
