### ISSUE TITLE
https://gurita4d.azurefd.net

### ISSUE THREAD

**Issue by gurita4d** [MatrixTM/MHDDoS#495]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

https://gurita4d.azurefd.net/

https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/

https://satriaitem.store/register?ref=u7UkQ4Yu

https://menang8c.net/register?ref=y0NosTw

https://cuanhabisslot.site/register

https://www.dewaraja88.xn--6frz82g/register

https://gogo77.vip/register

https://1131jp.org/register/W68JPLD3

https://kaki777.info/?ref=akunvip8721

https://airbet88maxwin.fun/register?ref=b0gQfQA

https://delta288real.site/?ref=akunvip8721

https://slot5000.cc

https://kilauhoki.net/

https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#

https://arjuna4d2.org/

https://perak777mpo.com/

https://www.harga88.co/

https://spin68.pro/

### Screenshots

https://gurita4d.azurefd.net/   https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/  https://satriaitem.store/register?ref=u7UkQ4Yu  https://menang8c.net/register?ref=y0NosTw  https://cuanhabisslot.site/register  https://www.dewaraja88.xn--6frz82g/register  https://gogo77.vip/register  https://1131jp.org/register/W68JPLD3  https://kaki777.info/?ref=akunvip8721  https://airbet88maxwin.fun/register?ref=b0gQfQA  https://delta288real.site/?ref=akunvip8721   https://slot5000.cc   https://kilauhoki.net/   https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#  https://arjuna4d2.org/  https://perak777mpo.com/  https://www.harga88.co/  https://spin68.pro/

### Please provide a link to a minimal reproduction of the bug

https://gurita4d.azurefd.net/   https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/  https://satriaitem.store/register?ref=u7UkQ4Yu  https://menang8c.net/register?ref=y0NosTw  https://cuanhabisslot.site/register  https://www.dewaraja88.xn--6frz82g/register  https://gogo77.vip/register  https://1131jp.org/register/W68JPLD3  https://kaki777.info/?ref=akunvip8721  https://airbet88maxwin.fun/register?ref=b0gQfQA  https://delta288real.site/?ref=akunvip8721   https://slot5000.cc   https://kilauhoki.net/   https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#  https://arjuna4d2.org/  https://perak777mpo.com/  https://www.harga88.co/  https://spin68.pro/

### Relevant log output

```shell
https://gurita4d.azurefd.net/


https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/

https://satriaitem.store/register?ref=u7UkQ4Yu

https://menang8c.net/register?ref=y0NosTw

https://cuanhabisslot.site/register

https://www.dewaraja88.xn--6frz82g/register

https://gogo77.vip/register

https://1131jp.org/register/W68JPLD3

https://kaki777.info/?ref=akunvip8721

https://airbet88maxwin.fun/register?ref=b0gQfQA

https://delta288real.site/?ref=akunvip8721


https://slot5000.cc


https://kilauhoki.net/


https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#

https://arjuna4d2.org/

https://perak777mpo.com/

https://www.harga88.co/

https://spin68.pro/
```

### Additional context

https://gurita4d.azurefd.net/

https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/

https://satriaitem.store/register?ref=u7UkQ4Yu

https://menang8c.net/register?ref=y0NosTw

https://cuanhabisslot.site/register

https://www.dewaraja88.xn--6frz82g/register

https://gogo77.vip/register

https://1131jp.org/register/W68JPLD3

https://kaki777.info/?ref=akunvip8721

https://airbet88maxwin.fun/register?ref=b0gQfQA

https://delta288real.site/?ref=akunvip8721

https://slot5000.cc

https://kilauhoki.net/

https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#

https://arjuna4d2.org/

https://perak777mpo.com/

https://www.harga88.co/

https://spin68.pro/

### Your code

```true
https://gurita4d.azurefd.net/


https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/

https://satriaitem.store/register?ref=u7UkQ4Yu

https://menang8c.net/register?ref=y0NosTw

https://cuanhabisslot.site/register

https://www.dewaraja88.xn--6frz82g/register

https://gogo77.vip/register

https://1131jp.org/register/W68JPLD3

https://kaki777.info/?ref=akunvip8721

https://airbet88maxwin.fun/register?ref=b0gQfQA

https://delta288real.site/?ref=akunvip8721


https://slot5000.cc


https://kilauhoki.net/


https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#

https://arjuna4d2.org/

https://perak777mpo.com/

https://www.harga88.co/

https://spin68.pro/
```

**Comment by gurita4d** [comment]
https://gurita4d.azurefd.net/


https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/

https://satriaitem.store/register?ref=u7UkQ4Yu

https://menang8c.net/register?ref=y0NosTw

https://cuanhabisslot.site/register

https://www.dewaraja88.xn--6frz82g/register

https://gogo77.vip/register

https://1131jp.org/register/W68JPLD3

https://kaki777.info/?ref=akunvip8721

https://airbet88maxwin.fun/register?ref=b0gQfQA

https://delta288real.site/?ref=akunvip8721


https://slot5000.cc


https://kilauhoki.net/


https://crai.santototunja.edu.co/wp-content/uploads/reff-hunter/#

https://arjuna4d2.org/

https://perak777mpo.com/

https://www.harga88.co/

https://spin68.pro/

**Comment by ramagansid1337** [comment]
pngin di ddos bg? wkw
