### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by Ahancom** [MatrixTM/MHDDoS#497]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
line 28, in <module>
from pyroxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'pyroxy'
```

### What happened (Describe the bug) ?

I can run L4 fine on windows, but after getting the code to Linux it keeps producing this error.
Both python 3.11.4 and 3.9.7 have run and produced this error.

### Screenshots

https://imgur.com/a/MRvoeVE

**Comment by Willie199** [comment]
pls I tried registering for imgur but to no avail pls the recapcha loaded
more than once so I get registered due to my network failure but now I'm
really ready to set up how can I get it started again?
