### ISSUE TITLE
Wheel package causing last 2 requirments to fail

### ISSUE THREAD

**Issue by adnanhaddad** [MatrixTM/MHDDoS#508]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
- OS: Windows (Sandbox)
- Python Version [e.g. 3.12.0]
```

### What happened (Describe the bug) ?

$ python -m pip install git+https://github.com/MHProDev/PyRoxy.git
Collecting git+https://github.com/MHProDev/PyRoxy.git
  Cloning https://github.com/MHProDev/PyRoxy.git to c:\users\wdagutilityaccount\appdata\local\temp\pip-req-build-8cqk04lw
  Running command git clone --filter=blob:none --quiet https://github.com/MHProDev/PyRoxy.git 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-req-build-8cqk04lw'
  Resolved https://github.com/MHProDev/PyRoxy.git to commit ea0f88dbc0573292ba5672124f69e4e7a31b544d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting maxminddb>=2.2.0 (from PyRoxy==1.0b5)
  Using cached maxminddb-2.4.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.27.1 in c:\program files\python312\lib\site-packages (from PyRoxy==1.0b5) (2.31.0)
Collecting yarl>=1.7.2 (from PyRoxy==1.0b5)
  Using cached yarl-1.9.2.tar.gz (184 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pysocks>=1.7.1 (from PyRoxy==1.0b5)
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python312\lib\site-packages (from requests>=2.27.1->PyRoxy==1.0b5) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python312\lib\site-packages (from requests>=2.27.1->PyRoxy==1.0b5) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python312\lib\site-packages (from requests>=2.27.1->PyRoxy==1.0b5) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python312\lib\site-packages (from requests>=2.27.1->PyRoxy==1.0b5) (2023.7.22)
Collecting multidict>=4.0 (from yarl>=1.7.2->PyRoxy==1.0b5)
  Using cached multidict-6.0.4.tar.gz (51 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: PyRoxy, yarl, multidict
  Building wheel for PyRoxy (pyproject.toml) ... done
  Created wheel for PyRoxy: filename=PyRoxy-1.0b5-py3-none-any.whl size=2830064 sha256=83f8bab45c0b4f9d5e25e734fe1a65f0cdc9dda94e7050044da5592e9bf61e3a
  Stored in directory: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-ephem-wheel-cache-0hd1hy3x\wheels\62\64\94\d36f786478ba0182e1c764c9786e9cae0a15376a69b125694a
  Building wheel for yarl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-build-env-rh4ghx17\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      **********************
      * Accelerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting.py -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting_py.py -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_url.py -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\__init__.py -> build\lib.win-amd64-cpython-312\yarl
      running egg_info
      writing yarl.egg-info\PKG-INFO
      writing dependency_links to yarl.egg-info\dependency_links.txt
      writing requirements to yarl.egg-info\requires.txt
      writing top-level names to yarl.egg-info\top_level.txt
      reading manifest file 'yarl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.cache' found anywhere in distribution
      warning: no previously-included files found matching 'yarl\*.html'
      warning: no previously-included files found matching 'yarl\*.so'
      warning: no previously-included files found matching 'yarl\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info\SOURCES.txt'
      copying yarl\__init__.pyi -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting_c.pyi -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\_quoting_c.pyx -> build\lib.win-amd64-cpython-312\yarl
      copying yarl\py.typed -> build\lib.win-amd64-cpython-312\yarl
      running build_ext
      building 'yarl._quoting_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\multidict
      copying multidict\_abc.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_compat.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict_base.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\_multidict_py.py -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\__init__.py -> build\lib.win-amd64-cpython-312\multidict
      running egg_info
      writing multidict.egg-info\PKG-INFO
      writing dependency_links to multidict.egg-info\dependency_links.txt
      writing top-level names to multidict.egg-info\top_level.txt
      reading manifest file 'multidict.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict\_multidict.html'
      warning: no previously-included files found matching 'multidict\*.so'
      warning: no previously-included files found matching 'multidict\*.pyd'
      warning: no previously-included files found matching 'multidict\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info\SOURCES.txt'
      C:\Users\WDAGUtilityAccount\AppData\Local\Temp\pip-build-env-e7rlwqwp\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-312\multidict 
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Successfully built PyRoxy
Failed to build yarl multidict
ERROR: Could not build wheels for yarl, multidict, which is required to install pyproject.toml-based projects

### Screenshots

https://imgur.com/a/XDm1D3P

**Comment by Donartus** [comment]
You need to fork the repo and update yarl from 1.7.2 to 1.9.2 (requirements.txt)

**Comment by greenteabots** [comment]
I have had same issues also that the DEFENDER blocked install of wheels impacket etc....

**Comment by Donartus** [comment]
Oh shoot
