### ISSUE TITLE
[BUG Report]: Your program had a shell / trojan in it

### ISSUE THREAD

**Issue by st1tchsecurity** [MatrixTM/MHDDoS#517]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
All I'm going to say is you're advertising malicious software. It's a trick to get others to install your trojan that you packed into the DDoS tool. Nice try though.
```

### What happened (Describe the bug) ?

Scanned the program, found that the Pip file included downloading a trojan / shell. This guy is a scammer and hacker.

### Screenshots

http://thisisdumb.com

### Additional context

Stop trying to scam people and infect their computers.

**Comment by st1tchsecurity** [comment]
Seriously screw off with that. Especially when others are hackers / researchers too >_>

**Comment by mrzt721010** [comment]
OH YEAH? If you think so, then DON'T use it

**Comment by st1tchsecurity** [comment]
Well then don't be a scammer lol. This wasn't for you btw, this was so other people don't get scammed by you. Your virus programming sucks btw it was picked up by defender immediately, you probably should look at ways of obfuscation.

**Comment by st1tchsecurity** [comment]
You can build your own crypter you know instead of immediately getting your virus caught. Nice try though. But go off.

**Comment by mrzt721010** [comment]
Any Proof?

**Comment by mrzt721010** [comment]
Any proof in the code?

**Comment by st1tchsecurity** [comment]
Yes and how about I just report all the IPs I pulled off the callback of the shell to CISA and IC3 and turn them into Github too. 
![Capture](https://github.com/MatrixTM/MHDDoS/assets/105241362/62748d13-1052-4737-8dd6-573fa980c118)

Would that be okay, since you're doing nothing wrong? Hope none of these are yours. I'm done contacting you, but just know that I do have these IPs. I will report them. You don't have my IP, you don't have any information about me. Maybe don't make crappy python malware with IP callbacks next time. Bye now.

**Comment by mrzt721010** [comment]
That's okay 👍🏻☺️

**Comment by natesworks** [comment]
lmfao
