### ISSUE TITLE
GetUserSPNs.py is a virus. 💀 

### ISSUE THREAD

**Issue by Pix-10** [MatrixTM/MHDDoS#519]
Is this a real virus?

**Comment by Pix-10** [comment]
<img width="435" alt="Screenshot 2023-11-24 131520" src="https://github.com/MatrixTM/MHDDoS/assets/128715251/098d9fc3-49e1-402c-9795-081b0a655bf7">

**Comment by mxrcode** [comment]
It is part of the package used by the soft: [impacket](https://github.com/fortra/impacket)

**Comment by mrzt721010** [comment]
https://github.com/fortra/impacket
