### ISSUE TITLE
[BUG Report]:跑不满宽带

### ISSUE THREAD

**Issue by 473845166** [MatrixTM/MHDDoS#531]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

线程开到5万了。宽带还是一半
![1706950390259](https://github.com/MatrixTM/MHDDoS/assets/93697913/c2ae518b-16ed-4c63-81f2-67907ef4ee3e)
而已

### Screenshots

https://github.com/MatrixTM/MHDDoS/assets/93697913/c2ae518b-16ed-4c63-81f2-67907ef4ee3e

### Relevant log output

```shell
C:\Users\wen\Desktop\5\MHDDoS\.venv\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't
 match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
[16:47:30 - WARNING] Thread is higher than 1000
[16:47:30 - INFO] Proxy Count: 850
[16:47:40 - INFO] Attack Started to 43.249.195.61 with BYPASS method for 3600 seconds, threads: 50100!
```

### Additional context

线程开到5万了。宽带还是一般而已

### Your code

```true
线程开到5万了。宽带还是一般而已
```

**Comment by mrzt721010** [comment]
If you think that we use Google Translate to help you, you are very wrong

**Comment by Pochinki98** [comment]
uh i think he isn't rude and he explain his issue correctly but just in another lang...
maybe we should be more patient but not just close a unsolved issue and leave a puzzle here right?
he is speaking that he has used so many threads to attack someone but his bandwidth was just half-used actually.he was confused about why the script cant run more perfectly.
btw i dont think it's proper to interrupt a issue in a unreasonale way.
这边跟老哥说一下，那个可能是python3自己的问题，python3有自己的线程限制，大概是1000上下，即使你调到五万了估计也是1000左右的最大值，如果你嫌不爽的话可以搞个screen然后开两个screen同时跑脚本试试。
