### ISSUE TITLE
[BUG Report]: i have a bug

### ISSUE THREAD

**Issue by kuba-bit** [MatrixTM/MHDDoS#536]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
OS : Windows 10 PRO

- Installed Requirements Version 
cloudscraper==1.2.71
certifi==2022.12.7
dnspython==2.2.1
requests==2.27.1
impacket==0.10.0
psutil>=5.9.3
icmplib>=2.1.1
pyasn1==0.4.8
pyroxy @ git+https://github.com/MatrixTM/PyRoxy.git
yarl>=1.9.2 

- Python Version 3.12.1
```

### What happened (Describe the bug) ?

C:\Users\Kuba\MHDDoS\start.py:168: SyntaxWarning: invalid escape sequence '\d'
  IP = compile("(?:\d{1,3}\.){3}\d{1,3}")

### Screenshots

https://imgur.com/a/T6311bb

### Relevant log output

```shell
C:\Users\Kuba\MHDDoS\start.py:168: SyntaxWarning: invalid escape sequence '\d'
  IP = compile("(?:\d{1,3}\.){3}\d{1,3}")
C:\Users\Kuba\MHDDoS\start.py:169: SyntaxWarning: invalid escape sequence '\d'
  protocolRex = compile('"protocol":(\d+)')
```

**Comment by sasouraaa** [comment]
Same problem here
