### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by MrLucifer-pro** [MatrixTM/MHDDoS#538]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

A bug happened!

### Screenshots

https://imgur.com/a/T6311bb

### Please provide a link to a minimal reproduction of the bug

https://docs.python.org

**Comment by Mythic5** [comment]
I have this too, Did u find a soluition?

**Comment by Mythic5** [comment]
I have this too, Did you find a solution?
