### ISSUE TITLE
Reflector file missing

### ISSUE THREAD

**Issue by pjbish** [MatrixTM/MHDDoS#540]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
Hi.

When I'm running python3 start.py dns 1xx.xxx.xxx.xxx:53 100 3600 dns.txt

I get this error "The reflector file doesn't exist"

I'm trying to build the reflectors file. A couple of issues I'm hoping someone can help with .

1) I get the following error when running zmap -p53 --output-filter='sport=53' -Mudp --probe-args=file:dns.pkt -f "saddr udp_pkt_size" -o dns.txt

"udp: could not open UDP data file 'localtime'"

2) Is it possible to build the reflector file manually ? If so, what needs to be in it, and which directory should it be in to run the DNS Amplification (L4) ?

Any idea how to resolve this (Ubuntu 20.04 )
```

### What happened (Describe the bug) ?

I'm trying to build the reflectors file. A couple of issues I'm hoping someone can help with .

1) I get the following error when running zmap -p53 --output-filter='sport=53' -Mudp --probe-args=file:dns.pkt -f "saddr udp_pkt_size" -o dns.txt

"udp: could not open UDP data file 'localtime'"

2) Is it possible to build the reflector file manually ? If so, what needs to be in it, and which directory should it be in to run the DNS Amplification (L4) ?

Any idea how to resolve this (Ubuntu 20.04 )

### Screenshots

https://imgur.com/a/v7obfdJ

### Additional context

Could you provide location and format for the reflector file please

**Comment by Ostring** [comment]
The same goes for me.
