### ISSUE TITLE
Brother Help me

### ISSUE THREAD

**Issue by kukkalu** [MatrixTM/MHDDoS#543]
### Which section is this feature request for?

L4 (DDoS Attack Layer 4)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to do server freeze.. Bgmi like pubg game.. It was we got ip and port with scrapping and we need to make ddos on lobby to make all offline.. After that we can play and kill offline kills.. Please sir how to do this.. I tried this udp flow but not worked.. Any solution... Some people are doing it working for ddos attck 
![IMG_20240417_150650_600](https://github.com/MatrixTM/MHDDoS/assets/61946705/c4cd9e0f-fd2e-4bbe-b77a-6d6530ff6865)

### Describe the solution you'd like

Just need that method only

### Additional context

Very use full sir l
Please explain atleast to me

**Comment by kukkalu** [comment]
Present script will work now?

**Comment by kukkalu** [comment]
I send udp flood brother.. But nothing happens.. Send 15GB

**Comment by MrNAWABTY** [comment]
Script file help me
