### ISSUE TITLE
[BUG Report]:install error

### ISSUE THREAD

**Issue by do02fw** [MatrixTM/MHDDoS#553]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: [e.g. Ubuntu] Ubuntu 24.04
- Installed Requirements Version [e.g. PyRoxy1.0b5] last
- Python Version [e.g. 3.8.x] 3.12
```

### What happened (Describe the bug) ?

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
![1](https://github.com/MatrixTM/MHDDoS/assets/138294823/8c86d930-4b6b-4462-9243-3fc7a6f277b8)

### Screenshots

https://github.com/MatrixTM/MHDDoS/assets/138294823/8c86d930-4b6b-4462-9243-3fc7a6f277b8

**Comment by BotSabugogrosso** [comment]
install with virtual environment: venv
