### ISSUE TITLE
how run?

### ISSUE THREAD

**Issue by Terator166** [MatrixTM/MHDDoS#562]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

how i run it please?

### Describe the solution you'd like

i installed it, but nothing else, i cant run it

**Comment by Lefoxxxx** [comment]
Use command prompt. Locate the path of the folder, it should be in C:\Users\'yourname'\MHDDoS

After that, use PowerShell and go to the folder of where the folder is located using cd. E.g. "cd C:\Users\'yourname'\MHDDoS

Once you are in the folder in PowerShell, type the following without these quote marks 'python .\start.py' if that doesn't work, try 'python3 .\start.py' 

If it still doesn't work, your installation failed and you need to re-install

Hope this help! Remember to only DDOS people with their consent and knowledge, use it responsibly.
