### ISSUE TITLE
[BUG Report]: CLOSES WHEN I OPEN

### ISSUE THREAD

**Issue by Via33nek** [MatrixTM/MHDDoS#565]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

A bug happened!
![Zrzut ekranu 2024-07-08 110010](https://github.com/MatrixTM/MHDDoS/assets/110767820/5a54d609-dc30-40c9-9926-2e69f12b9c12)

### Screenshots

provided in upper section

### Please provide a link to a minimal reproduction of the bug

w

**Comment by imtryingtoRAID** [comment]
just get better

**Comment by GonerRequiem1** [comment]
did anyone find a fix
