### ISSUE TITLE
[BUG Report]: Tool is broken, doesn't work as advertised, wiki docs outdated.... L4 doesnt use proxies & is sending packets from my IP / half the proxy links are 404 / tool doesnt check or download proxy links /  should have more & better options

### ISSUE THREAD

**Issue by hazeyez** [MatrixTM/MHDDoS#570]
### Version

2.4 (Default)

### Which section is the problem?

L4 (DDoS Attack Layer 4)

### Please complete the following information

```true
- OS: Ubuntu 22.04
- Installed Requirements Version: all current
- Python Version: 3.10.12
```

### What happened (Describe the bug) ?

Tool is broken; 
- doesn't work as advertised, 
- wiki docs outdated & poorly structure.... 
- L4 doesnt use proxies & is sending packets from my IP 
- half the proxy links are 404
- tool doesnt check or download proxy links 
- should have more & better options such as TCP RST packets, and ability to craft packet sizes, etc

The biggest issue here is that you advertise that L4 works with proxies, and besides the proxy functionality not working - it sends packets from user's IP. 

That is HIGHLY irresponsible for you to keep the repo up and advertised as such. Thankfully I was only testing on my own server. 

I thought this was a decent stress tool but clearly not.

### Screenshots

https://i.ibb.co/PT8wG7B/111.png

**Comment by mrzt721010** [comment]
just get better

**Comment by hazeyez** [comment]
@mrzt721010  okay, do you care to address any of the concerns at least about the tool A) not downloading proxy lists, and B) not using the proxies if I supply them? I ran it exactly as detailed in the docs.

**Comment by mrzt721010** [comment]
no I don't

**Comment by interbiznw** [comment]
> no I don't

lmao same
