### ISSUE TITLE
help pls install on kali linux

### ISSUE THREAD

**Issue by guwanna** [MatrixTM/MHDDoS#573]
### Which section is this feature request for?

Other

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

i am tried install this tool, but it just doesn't work for me

### Describe the solution you'd like

i am want help with the installation

### Additional context

i do not know to write here :)

**Comment by lolbatch** [comment]
git clone https://github.com/MatrixTM/MHDDoS
pip install -r requirements.txt
python3 start.py

**Comment by zZang32** [comment]
Could you upload some type of screenshots of the issues it throws you? So me or someone else, can actually help you providing information about how to fix it
