### ISSUE TITLE
Why does the proxy list keep showing up because it's empty?

### ISSUE THREAD

**Issue by hamid0901** [MatrixTM/MHDDoS#584]
![image](https://github.com/user-attachments/assets/ecdb5123-b78d-410c-aa9f-a0ca396a1119)
this is my proxies list download from proxyscrape.com
![image](https://github.com/user-attachments/assets/51f071f0-be16-4d23-a95b-f9caccd69c1a)
why proxy empty?

**Comment by DanHouseman** [comment]
the proxy list supplied defaults to the ./files/proxies/ folder. If you want to use a file relative to start.py it needs to be ./proxies.txt else it will be ./files/proxies/proxies.txt

**Comment by DanHouseman** [comment]
@hamid0901 If you have any further questions or need clarification don't hesitate. :)

**Comment by mrzt721010** [comment]
✅

**Comment by hamid0901** [comment]
Thank you for your detailed response. However, I have a question: Why does the forumzar.com server go down or slow down when attacked using web-based DDoS tools, but when using MHDDoS, the server doesn't slow down or go down?

![image](https://github.com/user-attachments/assets/cd2d9372-2c08-4fd2-91c1-71307652a37c)
![image](https://github.com/user-attachments/assets/6ffab285-a3cf-4807-9349-9150f42b5f5a)
